/content/drive/MyDrive/research_discourse_relation/discourse_relation_explainability
num_added_tokens: 16, added_special_tokens: <NOUN>,<PRONOUN>,<ADJECTIVAL-NOUN>,<PRENOUN-ADJECTIVAL>,<ADVERB>,<CONJUNCTION>,<INTERJECTION>,<VERB>,<ADJECTIVE>,<AUXILIARY-VERB>,<PARTICLE>,<PREFIX>,<SUFFIX>,<SYMBOL>,<AUXILIARY-SYMBOL>,<BLANK>
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at cl-tohoku/bert-base-japanese-v3 and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
  0%|          | 0/11 [00:00<?, ?it/s]/usr/lib/python3.10/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING] WON'T CONVERT resume_in_forward /usr/local/lib/python3.10/dist-packages/transformers/models/bert/modeling_bert.py line 1562
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING] due to:
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING] Traceback (most recent call last):
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/convert_frame.py", line 727, in _convert_frame
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     result = inner_convert(frame, cache_entry, hooks, frame_state)
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/convert_frame.py", line 383, in _convert_frame_assert
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     compiled_product = _compile(
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/convert_frame.py", line 646, in _compile
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     guarded_code = compile_inner(code, one_graph, hooks, transform)
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/utils.py", line 244, in time_wrapper
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     r = func(*args, **kwargs)
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/convert_frame.py", line 562, in compile_inner
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     out_code = transform_code_object(code, transform)
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/bytecode_transformation.py", line 1033, in transform_code_object
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     transformations(instructions, code_options)
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/convert_frame.py", line 151, in _fn
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     return fn(*args, **kwargs)
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/convert_frame.py", line 527, in transform
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     tracer.run()
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/symbolic_convert.py", line 2128, in run
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     super().run()
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/symbolic_convert.py", line 818, in run
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     and self.step()
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/symbolic_convert.py", line 781, in step
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     getattr(self, inst.opname)(inst)
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/symbolic_convert.py", line 2243, in RETURN_VALUE
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     self.output.compile_subgraph(
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/output_graph.py", line 945, in compile_subgraph
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     self.compile_and_call_fx_graph(tx, pass2.graph_output_vars(), root)
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/lib/python3.10/contextlib.py", line 79, in inner
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     return func(*args, **kwds)
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/output_graph.py", line 1087, in compile_and_call_fx_graph
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     compiled_fn = self.call_user_compiler(gm)
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/utils.py", line 244, in time_wrapper
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     r = func(*args, **kwargs)
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/output_graph.py", line 1159, in call_user_compiler
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/output_graph.py", line 1140, in call_user_compiler
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     compiled_fn = compiler_fn(gm, self.example_inputs())
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/repro/after_dynamo.py", line 117, in debug_wrapper
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     compiled_gm = compiler_fn(gm, example_inputs)
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/__init__.py", line 1668, in __call__
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     return compile_fx(model_, inputs_, config_patches=self.config)
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/compile_fx.py", line 1168, in compile_fx
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     return aot_autograd(
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/backends/common.py", line 55, in compiler_fn
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     cg = aot_module_simplified(gm, example_inputs, **kwargs)
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_functorch/aot_autograd.py", line 887, in aot_module_simplified
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     compiled_fn = create_aot_dispatcher_function(
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/utils.py", line 244, in time_wrapper
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     r = func(*args, **kwargs)
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_functorch/aot_autograd.py", line 600, in create_aot_dispatcher_function
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     compiled_fn = compiler_fn(flat_fn, fake_flat_args, aot_config, fw_metadata=fw_metadata)
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 425, in aot_wrapper_dedupe
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     return compiler_fn(flat_fn, leaf_flat_args, aot_config, fw_metadata=fw_metadata)
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 630, in aot_wrapper_synthetic_base
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     return compiler_fn(flat_fn, flat_args, aot_config, fw_metadata=fw_metadata)
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_functorch/_aot_autograd/jit_compile_runtime_wrappers.py", line 97, in aot_dispatch_base
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     compiled_fw = compiler(fw_module, updated_flat_args)
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/utils.py", line 244, in time_wrapper
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     r = func(*args, **kwargs)
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/compile_fx.py", line 1100, in fw_compiler_base
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     return inner_compile(
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/repro/after_aot.py", line 83, in debug_wrapper
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     inner_compiled_fn = compiler_fn(gm, example_inputs)
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/debug.py", line 305, in inner
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     return fn(*args, **kwargs)
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/lib/python3.10/contextlib.py", line 79, in inner
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     return func(*args, **kwds)
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/compile_fx.py", line 320, in compile_fx_inner
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     compiled_graph = fx_codegen_and_compile(
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/compile_fx.py", line 550, in fx_codegen_and_compile
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     compiled_fn = graph.compile_to_fn()
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/graph.py", line 1116, in compile_to_fn
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     return self.compile_to_module().call
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/utils.py", line 244, in time_wrapper
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     r = func(*args, **kwargs)
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/graph.py", line 1070, in compile_to_module
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     mod = PyCodeCache.load_by_key_path(
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/codecache.py", line 1892, in load_by_key_path
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     exec(code, mod.__dict__, mod.__dict__)
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/tmp/torchinductor_root/cf/ccftm5in3tgbhiniohv7pnqguv3fsdar4vh4jfin2d7cwe7epywm.py", line 28, in <module>
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     triton_red_fused__log_softmax_nll_loss_forward_0 = async_compile.triton('triton_', '''
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/codecache.py", line 2448, in triton
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     future = self.process_pool().submit(
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/lib/python3.10/concurrent/futures/process.py", line 720, in submit
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     raise BrokenProcessPool(self._broken)
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING] torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING] BrokenProcessPool: A child process terminated abruptly, the process pool is not usable anymore
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING] Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING] Traceback (most recent call last):
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/convert_frame.py", line 727, in _convert_frame
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     result = inner_convert(frame, cache_entry, hooks, frame_state)
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/convert_frame.py", line 383, in _convert_frame_assert
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     compiled_product = _compile(
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/convert_frame.py", line 646, in _compile
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     guarded_code = compile_inner(code, one_graph, hooks, transform)
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/utils.py", line 244, in time_wrapper
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     r = func(*args, **kwargs)
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/convert_frame.py", line 562, in compile_inner
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     out_code = transform_code_object(code, transform)
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/bytecode_transformation.py", line 1033, in transform_code_object
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     transformations(instructions, code_options)
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/convert_frame.py", line 151, in _fn
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     return fn(*args, **kwargs)
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/convert_frame.py", line 527, in transform
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     tracer.run()
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/symbolic_convert.py", line 2128, in run
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     super().run()
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/symbolic_convert.py", line 818, in run
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     and self.step()
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/symbolic_convert.py", line 781, in step
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     getattr(self, inst.opname)(inst)
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/symbolic_convert.py", line 2243, in RETURN_VALUE
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     self.output.compile_subgraph(
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/output_graph.py", line 945, in compile_subgraph
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     self.compile_and_call_fx_graph(tx, pass2.graph_output_vars(), root)
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/lib/python3.10/contextlib.py", line 79, in inner
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     return func(*args, **kwds)
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/output_graph.py", line 1087, in compile_and_call_fx_graph
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     compiled_fn = self.call_user_compiler(gm)
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/utils.py", line 244, in time_wrapper
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     r = func(*args, **kwargs)
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/output_graph.py", line 1159, in call_user_compiler
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/output_graph.py", line 1140, in call_user_compiler
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     compiled_fn = compiler_fn(gm, self.example_inputs())
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/repro/after_dynamo.py", line 117, in debug_wrapper
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     compiled_gm = compiler_fn(gm, example_inputs)
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/__init__.py", line 1668, in __call__
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     return compile_fx(model_, inputs_, config_patches=self.config)
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/compile_fx.py", line 1168, in compile_fx
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     return aot_autograd(
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/backends/common.py", line 55, in compiler_fn
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     cg = aot_module_simplified(gm, example_inputs, **kwargs)
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_functorch/aot_autograd.py", line 887, in aot_module_simplified
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     compiled_fn = create_aot_dispatcher_function(
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/utils.py", line 244, in time_wrapper
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     r = func(*args, **kwargs)
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_functorch/aot_autograd.py", line 600, in create_aot_dispatcher_function
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     compiled_fn = compiler_fn(flat_fn, fake_flat_args, aot_config, fw_metadata=fw_metadata)
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 425, in aot_wrapper_dedupe
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     return compiler_fn(flat_fn, leaf_flat_args, aot_config, fw_metadata=fw_metadata)
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 630, in aot_wrapper_synthetic_base
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     return compiler_fn(flat_fn, flat_args, aot_config, fw_metadata=fw_metadata)
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_functorch/_aot_autograd/jit_compile_runtime_wrappers.py", line 97, in aot_dispatch_base
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     compiled_fw = compiler(fw_module, updated_flat_args)
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/utils.py", line 244, in time_wrapper
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     r = func(*args, **kwargs)
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/compile_fx.py", line 1100, in fw_compiler_base
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     return inner_compile(
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/repro/after_aot.py", line 83, in debug_wrapper
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     inner_compiled_fn = compiler_fn(gm, example_inputs)
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/debug.py", line 305, in inner
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     return fn(*args, **kwargs)
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/lib/python3.10/contextlib.py", line 79, in inner
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     return func(*args, **kwds)
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/compile_fx.py", line 320, in compile_fx_inner
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     compiled_graph = fx_codegen_and_compile(
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/compile_fx.py", line 550, in fx_codegen_and_compile
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     compiled_fn = graph.compile_to_fn()
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/graph.py", line 1116, in compile_to_fn
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     return self.compile_to_module().call
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/utils.py", line 244, in time_wrapper
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     r = func(*args, **kwargs)
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/graph.py", line 1070, in compile_to_module
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     mod = PyCodeCache.load_by_key_path(
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/codecache.py", line 1892, in load_by_key_path
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     exec(code, mod.__dict__, mod.__dict__)
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/tmp/torchinductor_root/cf/ccftm5in3tgbhiniohv7pnqguv3fsdar4vh4jfin2d7cwe7epywm.py", line 28, in <module>
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     triton_red_fused__log_softmax_nll_loss_forward_0 = async_compile.triton('triton_', '''
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/codecache.py", line 2448, in triton
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     future = self.process_pool().submit(
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]   File "/usr/lib/python3.10/concurrent/futures/process.py", line 720, in submit
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]     raise BrokenProcessPool(self._broken)
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING] torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING] BrokenProcessPool: A child process terminated abruptly, the process pool is not usable anymore
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING] Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information
[2024-05-12 14:04:33,056] torch._dynamo.convert_frame: [WARNING]
  0%|          | 0/15 [00:00<?, ?it/s]/usr/lib/python3.10/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()[00:00<?, ?it/s]
epoch: None 	loss: 0.065231   	accuracy: 0.2575 	precision: 0.1848 	recall: 0.2304 	f1: 0.1233




  self.pid = os.fork()[00:00<?, ?it/s]

  self.pid = os.fork()[00:00<?, ?it/s]
epoch: 0 	loss: 0.001795   	accuracy: 0.7865 	precision: 0.2677 	recall: 0.3051 	f1: 0.2843
epoch: 0 	loss: 0.026983   	accuracy: 0.7784 	precision: 0.2785 	recall: 0.3221 	f1: 0.2972
  7%|▋         | 1/15 [01:33<21:45, 93/usr/lib/python3.10/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()[00:00<?, ?it/s]






  self.pid = os.fork()[00:00<?, ?it/s]
 13%|█▎        | 2/15 [01:47<10:09, 46/usr/lib/python3.10/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()[00:00<?, ?it/s]
  4%|▎         | 3/84 [00:00<00:13,  5.81it/s]
epoch: 1 	loss: 0.001506   	accuracy: 0.8240 	precision: 0.4032 	recall: 0.4322 	f1: 0.4110






  self.pid = os.fork()[00:00<?, ?it/s]
 20%|██        | 3/15 [02:02<06:25, 32/usr/lib/python3.10/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()[00:00<?, ?it/s]
epoch: 2 	loss: 0.000553   	accuracy: 0.8809 	precision: 0.4701 	recall: 0.4942 	f1: 0.4817
epoch: 2 	loss: 0.032110   	accuracy: 0.8503 	precision: 0.4231 	recall: 0.5100 	f1: 0.4558






  self.pid = os.fork()[00:00<?, ?it/s]
epoch: 3 	loss: 0.000150   	accuracy: 0.9416 	precision: 0.7358 	recall: 0.6954 	f1: 0.7141
epoch: 3 	loss: 0.023101   	accuracy: 0.9042 	precision: 0.6298 	recall: 0.6642 	f1: 0.6445
 27%|██▋       | 4/15 [02:16<04:37, 25/usr/lib/python3.10/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()[00:00<?, ?it/s]






 99%|█████████▉| 83/84 [00:02<00:00, 34.48it/s]
  self.pid = os.fork()[00:00<?, ?it/s]
 33%|███▎      | 5/15 [02:31<03:33, 21/usr/lib/python3.10/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()[00:00<?, ?it/s]
  8%|▊         | 7/84 [00:01<00:10,  7.49it/s]






  self.pid = os.fork()[00:00<?, ?it/s]
 40%|████      | 6/15 [02:45<02:51, 19/usr/lib/python3.10/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()[00:00<?, ?it/s]
  2%|▏         | 2/84 [00:00<00:17,  4.72it/s]
epoch: 5 	loss: 0.000043   	accuracy: 0.9685 	precision: 0.9770 	recall: 0.8741 	f1: 0.9161






  self.pid = os.fork()[00:00<?, ?it/s]
 47%|████▋     | 7/15 [03:00<02:20, 17/usr/lib/python3.10/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()[00:00<?, ?it/s]
epoch: 6 	loss: 0.000035   	accuracy: 0.9693 	precision: 0.7545 	recall: 0.7673 	f1: 0.7590
epoch: 6 	loss: 0.019978   	accuracy: 0.8982 	precision: 0.6308 	recall: 0.7137 	f1: 0.6363






  self.pid = os.fork()[00:00<?, ?it/s]
epoch: 7 	loss: 0.000033   	accuracy: 0.9738 	precision: 0.8569 	recall: 0.8743 	f1: 0.8446
epoch: 7 	loss: 0.034006   	accuracy: 0.8683 	precision: 0.5882 	recall: 0.5708 	f1: 0.5767
 53%|█████▎    | 8/15 [03:15<01:56, 16/usr/lib/python3.10/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()[00:00<?, ?it/s]






  self.pid = os.fork()[00:00<?, ?it/s]
 60%|██████    | 9/15 [03:29<01:36, 16/usr/lib/python3.10/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()[00:00<?, ?it/s]
  5%|▍         | 4/84 [00:00<00:12,  6.19it/s]
epoch: 8 	loss: 0.000030   	accuracy: 0.9880 	precision: 0.9655 	recall: 0.8150 	f1: 0.8214






  self.pid = os.fork()[00:00<?, ?it/s]
 67%|██████▋   | 10/15 [03:44<01:18, 1/usr/lib/python3.10/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()[00:00<?, ?it/s]
epoch: 9 	loss: 0.000023   	accuracy: 0.9933 	precision: 0.9929 	recall: 0.9631 	f1: 0.9771
epoch: 9 	loss: 0.023755   	accuracy: 0.8443 	precision: 0.6084 	recall: 0.6571 	f1: 0.6047






 24%|██▍       | 20/84 [00:00<00:02, 24.17it/s]
epoch: 10 	loss: 0.000017   	accuracy: 0.9933 	precision: 0.9937 	recall: 0.9624 	f1: 0.9771
epoch: 10 	loss: 0.023980   	accuracy: 0.8623 	precision: 0.8223 	recall: 0.7104 	f1: 0.6919
                                      /usr/lib/python3.10/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()[00:00<?, ?it/s]
 73%|███████▎  | 11/15 [03:59<01:01, 1/usr/lib/python3.10/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()[00:00<?, ?it/s]






  self.pid = os.fork()[00:00<?, ?it/s]
 73%|███████▎  | 11/15 [04:14<01:01, 15.48s/it]
epoch: 11 	loss: 0.000016   	accuracy: 0.9933 	precision: 0.9975 	recall: 0.9585 	f1: 0.9770
 80%|████████  | 12/15 [04:14<00:46, 1/usr/lib/python3.10/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()[00:00<?, ?it/s]






 95%|█████████▌| 80/84 [00:02<00:00, 34.57it/s]
epoch: 12 	loss: 0.000013   	accuracy: 0.9940 	precision: 0.9977 	recall: 0.9594 	f1: 0.9776
  self.pid = os.fork()[00:00<?, ?it/s]
 87%|████████▋ | 13/15 [04:29<00:30, 1/usr/lib/python3.10/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()[00:00<?, ?it/s]






  self.pid = os.fork()[00:00<?, ?it/s]
 93%|█████████▎| 14/15 [04:44<00:15, 1/usr/lib/python3.10/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()[00:00<?, ?it/s]
epoch: 13 	loss: 0.000012   	accuracy: 0.9940 	precision: 0.9931 	recall: 0.9640 	f1: 0.9777
epoch: 13 	loss: 0.024329   	accuracy: 0.8683 	precision: 0.8180 	recall: 0.7446 	f1: 0.7119






  self.pid = os.fork()[00:00<?, ?it/s]
epoch: 14 	loss: 0.000012   	accuracy: 0.9940 	precision: 0.9890 	recall: 0.9686 	f1: 0.9778
epoch: 14 	loss: 0.024682   	accuracy: 0.8683 	precision: 0.8180 	recall: 0.7446 	f1: 0.7119
100%|██████████| 15/15 [04:59<00:00, 19.96s/it]
  0%|          | 0/11 [00:00<?, ?it/s]/usr/lib/python3.10/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
  0%|          | 0/11 [00:00<?, ?it/s]/usr/lib/python3.10/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
No traceback available to show.
OptimizedModule(
  (_orig_mod): BertForSequenceClassification(
    (bert): BertModel(
      (embeddings): BertEmbeddings(
        (word_embeddings): Embedding(32784, 768)
        (position_embeddings): Embedding(512, 768)
        (token_type_embeddings): Embedding(2, 768)
        (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        (dropout): Dropout(p=0.1, inplace=False)
      )
      (encoder): BertEncoder(
        (layer): ModuleList(
          (0-11): 12 x BertLayer(
            (attention): BertAttention(
              (self): BertSelfAttention(
                (query): Linear(in_features=768, out_features=768, bias=True)
                (key): Linear(in_features=768, out_features=768, bias=True)
                (value): Linear(in_features=768, out_features=768, bias=True)
                (dropout): Dropout(p=0.1, inplace=False)
              )
              (output): BertSelfOutput(
                (dense): Linear(in_features=768, out_features=768, bias=True)
                (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
                (dropout): Dropout(p=0.1, inplace=False)
              )
            )
            (intermediate): BertIntermediate(
              (dense): Linear(in_features=768, out_features=3072, bias=True)
              (intermediate_act_fn): GELUActivation()
            )
            (output): BertOutput(
              (dense): Linear(in_features=3072, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
        )
      )
      (pooler): BertPooler(
        (dense): Linear(in_features=768, out_features=768, bias=True)
        (activation): Tanh()
      )
    )
    (dropout): Dropout(p=0.1, inplace=False)
    (classifier): Linear(in_features=768, out_features=5, bias=True)
  )
)
<class 'torch._dynamo.eval_frame.OptimizedModule'>
<class 'transformers.models.bert.modeling_bert.BertForSequenceClassification'>